- name: Deploy Docker Compose
  hosts: localhost

  tasks:
    - name: Create a new file for deployment
      file:
        path: ~/docker_services
        state: directory

    - name: Copy the files to the new directory
      copy:
        src: "{{ item }}"
        dest: ~/docker_services/
      with_items:
        - bash-script.sh
        - python-script.py
        - Dockerfile-bash
        - Dockerfile-python
        - docker-compose.yaml

    - name: Start Docker Compose
      community.docker.docker_compose:
        project_src: ~/docker_services
        state: present
