- name: Deploy Docker and Docker Compose 
  hosts: local
  become: true
  tasks:
    - name: Update package index
      apt:
        update_cache: yes

    - name: Install prerequisites for Docker installation
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker’s official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Install Docker and Docker Compose plugin
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Create a new directory for deployment
      file:
        path: ~/docker_services
        state: directory

    - name: Copy deployment files to the new directory
      copy:
        src: "{{ item }}"
        dest: ~/docker_services/
      with_items:
        - bash-script.sh
        - python-script.py
        - Dockerfile-bash
        - Dockerfile-python
        - docker-compose.yaml

    - name: Start Docker Compose services
      community.docker.docker_compose:
        project_src: ~/docker_services
        state: present
