# Use Python base image
FROM python:3.10-slim

# Upgrade pip
RUN pip install --upgrade pip

# Install necessary Python packages
RUN pip install \
    psutil \
    distro

# Copy the Python script
COPY python-script.py /python-script.py

# Run the script and unbuffer the output
CMD ["python3", "-u", "/python-script.py"]

