# Use Ubuntu as the base image
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && apt-get install -y \
    bash \
    apt-utils \
    lsb-release \
    util-linux \
    && rm -rf /var/lib/apt/lists/*

# Copy the bash script
COPY bash-script.sh /bash-script.sh

# Set executable permissions
RUN chmod +x /bash-script.sh

# Run the script
CMD ["/bash-script.sh"]
